## KBins with test

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
from sklearn.preprocessing import KBinsDiscretizer

In [2]:
diamonds_kbin = pd.read_csv('../../../001data/003preprocessing/002feature_engineering/diamonds_fe.csv')
diamonds_kbin

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,city,xyz/depth,xyz/carat,depth/table,depth/z,depth/carat,table/z,table/carat,carat/z,x/z,y/z,x/y,mass,volume,density,proportion,carat/depth,carat/table,volume/table,volume/depth
0,0,1.21,Premium,J,VS2,62.4,58.0,6.83,6.79,4.25,Dubai,3.158601,162.889855,1.075862,14.682353,51.570248,13.647059,47.933884,0.284706,1.607059,1.597647,1.005891,0.242,0.068946,3.51,5.455965,0.019391,0.020862,0.001189,0.001105
1,1,0.32,Very Good,H,VS2,63.0,57.0,4.35,4.38,2.75,Kimberly,0.831679,163.736719,1.105263,22.909091,196.875000,20.727273,178.125000,0.116364,1.581818,1.592727,0.993151,0.064,0.018234,3.51,3.464182,0.005079,0.005614,0.000320,0.000289
2,2,0.71,Fair,G,VS1,65.5,55.0,5.62,5.53,3.65,Las Vegas,1.731861,159.770268,1.190909,17.945205,92.253521,15.068493,77.464789,0.194521,1.539726,1.515068,1.016275,0.142,0.040456,3.51,4.257342,0.010840,0.012909,0.000736,0.000618
3,3,0.41,Good,D,SI1,63.8,56.0,4.68,4.72,3.00,Kimberly,1.038696,161.631220,1.139286,21.266667,155.609756,18.666667,136.585366,0.136667,1.560000,1.573333,0.991525,0.082,0.023362,3.51,3.681600,0.006426,0.007321,0.000417,0.000366
4,4,1.02,Ideal,G,SI1,60.5,59.0,6.55,6.51,3.95,Dubai,2.783967,165.127426,1.025424,15.316456,59.313725,14.936709,57.843137,0.258228,1.658228,1.648101,1.006144,0.204,0.058120,3.51,5.397532,0.016860,0.017288,0.000985,0.000961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,40450,1.34,Ideal,G,VS1,62.7,57.0,7.10,7.04,4.43,Antwerp,3.531565,165.245612,1.100000,14.153499,46.791045,12.866817,42.537313,0.302483,1.602709,1.589165,1.008523,0.268,0.076353,3.51,5.641535,0.021372,0.023509,0.001340,0.001218
40451,40451,2.02,Good,F,SI2,57.1,60.0,8.31,8.25,4.73,Madrid,5.679106,160.533156,0.951667,12.071882,28.267327,12.684989,29.702970,0.427061,1.756871,1.744186,1.007273,0.404,0.115100,3.51,7.247093,0.035377,0.033667,0.001918,0.002016
40452,40452,1.01,Ideal,H,SI1,62.7,56.0,6.37,6.42,4.01,Kimberly,2.615479,162.366885,1.119643,15.635910,62.079208,13.965087,55.445545,0.251870,1.588529,1.600998,0.992212,0.202,0.057550,3.51,5.099177,0.016108,0.018036,0.001028,0.000918
40453,40453,0.33,Ideal,J,VS1,61.9,54.3,4.45,4.47,2.76,Kimberly,0.886923,166.365273,1.139963,22.427536,187.575758,19.673913,164.545455,0.119565,1.612319,1.619565,0.995526,0.066,0.018803,3.51,3.603533,0.005331,0.006077,0.000346,0.000304
40454,40454,1.24,Ideal,I,SI1,62.0,58.0,6.83,6.88,4.25,London,3.221116,161.055806,1.068966,14.588235,50.000000,13.647059,46.774194,0.291765,1.607059,1.618824,0.992733,0.248,0.070655,3.51,5.528282,0.020000,0.021379,0.001218,0.001140

In [3]:
diamonds_kbin = diamonds_kbin[['proportion', 'depth/carat', 'table/carat', 'x/y', 'depth/table', 'volume/table', 'volume/depth']]
diamonds_kbin

,proportion,depth/carat,table/carat,x/y,depth/table,volume/table,volume/depth
0,5.455965,51.570248,47.933884,1.005891,1.075862,0.001189,0.001105
1,3.464182,196.875000,178.125000,0.993151,1.105263,0.000320,0.000289
2,4.257342,92.253521,77.464789,1.016275,1.190909,0.000736,0.000618
3,3.681600,155.609756,136.585366,0.991525,1.139286,0.000417,0.000366
4,5.397532,59.313725,57.843137,1.006144,1.025424,0.000985,0.000961
...,...,...,...,...,...,...,...
40450,5.641535,46.791045,42.537313,1.008523,1.100000,0.001340,0.001218
40451,7.247093,28.267327,29.702970,1.007273,0.951667,0.001918,0.002016
40452,5.099177,62.079208,55.445545,0.992212,1.119643,0.001028,0.000918
40453,3.603533,187.575758,164.545455,0.995526,1.139963,0.000346,0.000304
40454,5.528282,50.000000,46.774194,0.992733,1.068966,0.001218,0.001140

In [4]:
diamonds_test_kbin = pd.read_csv('../../../001data/003preprocessing/002feature_engineering/diamonds_test_fe.csv')
diamonds_test_kbin

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,city,xyz/depth,xyz/carat,depth/table,depth/z,depth/carat,table/z,table/carat,carat/z,x/z,y/z,x/y,mass,volume,density,proportion,carat/depth,carat/table,volume/table,volume/depth
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam,2.006489,159.249197,1.045000,17.084469,79.367089,16.348774,75.949367,0.215259,1.585831,1.604905,0.988115,0.158,0.045014,3.51,4.670272,0.012600,0.013167,0.000750,0.000718
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat,3.215235,163.441135,1.070175,14.593301,50.833333,13.636364,47.500000,0.287081,1.629187,1.648325,0.988389,0.240,0.068376,3.51,5.612548,0.019672,0.021053,0.001200,0.001121
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly,3.969111,157.247587,1.019672,13.610503,39.617834,13.347921,38.853503,0.343545,1.614880,1.601751,1.008197,0.314,0.089459,3.51,5.910460,0.025241,0.025738,0.001467,0.001438
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly,2.282032,161.770700,1.181481,16.358974,70.888889,13.846154,60.000000,0.230769,1.561538,1.571795,0.993475,0.180,0.051282,3.51,4.786115,0.014107,0.016667,0.000950,0.000804
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam,1.303615,163.994710,1.084483,19.717868,125.800000,18.181818,116.000000,0.156740,1.583072,1.595611,0.992141,0.100,0.028490,3.51,4.028918,0.007949,0.008621,0.000491,0.000453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam,1.517360,164.780000,1.105357,18.757576,108.596491,16.969697,98.245614,0.172727,1.621212,1.612121,1.005639,0.114,0.032479,3.51,4.312424,0.009208,0.010179,0.000580,0.000525
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City,1.872623,164.052321,1.130909,17.471910,87.605634,15.449438,77.464789,0.199438,1.603933,1.609551,0.996510,0.142,0.040456,3.51,4.595267,0.011415,0.012909,0.000736,0.000650
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv,1.881473,165.569607,1.120000,17.450425,88.000000,15.580737,78.571429,0.198300,1.628895,1.617564,1.007005,0.140,0.039886,3.51,4.650496,0.011364,0.012727,0.000725,0.000648
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat,2.021682,169.821321,1.031579,17.043478,84.000000,16.521739,81.428571,0.202899,1.695652,1.707246,0.993209,0.140,0.039886,3.51,4.993696,0.011905,0.012281,0.000700,0.000678
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City,1.047422,163.397850,1.134545,21.224490,156.000000,18.707483,137.500000,0.136054,1.598639,1.608844,0.993658,0.080,0.022792,3.51,3.780782,0.006410,0.007273,0.000414,0.000365

In [5]:
diamonds_test_kbin = diamonds_test_kbin[['proportion', 'depth/carat', 'table/carat', 'x/y', 'depth/table', 'volume/table', 'volume/depth']]
diamonds_test_kbin

,proportion,depth/carat,table/carat,x/y,depth/table,volume/table,volume/depth
0,4.670272,79.367089,75.949367,0.988115,1.045000,0.000750,0.000718
1,5.612548,50.833333,47.500000,0.988389,1.070175,0.001200,0.001121
2,5.910460,39.617834,38.853503,1.008197,1.019672,0.001467,0.001438
3,4.786115,70.888889,60.000000,0.993475,1.181481,0.000950,0.000804
4,4.028918,125.800000,116.000000,0.992141,1.084483,0.000491,0.000453
...,...,...,...,...,...,...,...
13480,4.312424,108.596491,98.245614,1.005639,1.105357,0.000580,0.000525
13481,4.595267,87.605634,77.464789,0.996510,1.130909,0.000736,0.000650
13482,4.650496,88.000000,78.571429,1.007005,1.120000,0.000725,0.000648
13483,4.993696,84.000000,81.428571,0.993209,1.031579,0.000700,0.000678
13484,3.780782,156.000000,137.500000,0.993658,1.134545,0.000414,0.000365

In [6]:
# concat with test
diamonds_kbin_w = pd.concat([diamonds_kbin, diamonds_test_kbin])
diamonds_kbin_w

,proportion,depth/carat,table/carat,x/y,depth/table,volume/table,volume/depth
0,5.455965,51.570248,47.933884,1.005891,1.075862,0.001189,0.001105
1,3.464182,196.875000,178.125000,0.993151,1.105263,0.000320,0.000289
2,4.257342,92.253521,77.464789,1.016275,1.190909,0.000736,0.000618
3,3.681600,155.609756,136.585366,0.991525,1.139286,0.000417,0.000366
4,5.397532,59.313725,57.843137,1.006144,1.025424,0.000985,0.000961
...,...,...,...,...,...,...,...
13480,4.312424,108.596491,98.245614,1.005639,1.105357,0.000580,0.000525
13481,4.595267,87.605634,77.464789,0.996510,1.130909,0.000736,0.000650
13482,4.650496,88.000000,78.571429,1.007005,1.120000,0.000725,0.000648
13483,4.993696,84.000000,81.428571,0.993209,1.031579,0.000700,0.000678
13484,3.780782,156.000000,137.500000,0.993658,1.134545,0.000414,0.000365

In [7]:
kbin_est = KBinsDiscretizer(n_bins=15, encode='ordinal', strategy='kmeans')
kbin_est.fit(diamonds_kbin_w)
diamonds_kbin_w = kbin_est.transform(diamonds_kbin_w)

In [8]:
diamonds_kbin_w = pd.DataFrame(diamonds_kbin_w)
diamonds_kbin_w

         0    1    2    3     4    5    6
0      7.0  1.0  1.0  5.0   8.0  3.0  3.0
1      0.0  9.0  8.0  4.0   9.0  0.0  0.0
2      3.0  3.0  3.0  6.0  12.0  1.0  1.0
3      1.0  6.0  6.0  3.0  11.0  0.0  0.0
4      6.0  2.0  2.0  5.0   5.0  2.0  2.0
...    ...  ...  ...  ...   ...  ...  ...
53935  3.0  4.0  4.0  5.0   9.0  1.0  1.0
53936  4.0  3.0  3.0  4.0  10.0  1.0  1.0
53937  4.0  3.0  3.0  5.0  10.0  1.0  1.0
53938  5.0  3.0  3.0  4.0   6.0  1.0  1.0
53939  1.0  6.0  6.0  4.0  10.0  0.0  0.0

[53940 rows x 7 columns]

In [9]:
diamonds_kbin_w.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

C:\Users\marym\AppData\Local\Temp\ipykernel_7004\1317053828.py:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  diamonds_kbin_w.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

In [10]:
diamonds_kbin_w

,proportion_kbw,depth/carat_kbw,table/carat_kbw,x/y_kbw,depth/table_kbw,volume/table_kbw,volume/depth_kbw
0,7.0,1.0,1.0,5.0,8.0,3.0,3.0
1,0.0,9.0,8.0,4.0,9.0,0.0,0.0
2,3.0,3.0,3.0,6.0,12.0,1.0,1.0
3,1.0,6.0,6.0,3.0,11.0,0.0,0.0
4,6.0,2.0,2.0,5.0,5.0,2.0,2.0
...,...,...,...,...,...,...,...
53935,3.0,4.0,4.0,5.0,9.0,1.0,1.0
53936,4.0,3.0,3.0,4.0,10.0,1.0,1.0
53937,4.0,3.0,3.0,5.0,10.0,1.0,1.0
53938,5.0,3.0,3.0,4.0,6.0,1.0,1.0
53939,1.0,6.0,6.0,4.0,10.0,0.0,0.0

In [11]:
diamonds_kbin_w = diamonds_kbin_w[:40455]
diamonds_kbin_w

,proportion_kbw,depth/carat_kbw,table/carat_kbw,x/y_kbw,depth/table_kbw,volume/table_kbw,volume/depth_kbw
0,7.0,1.0,1.0,5.0,8.0,3.0,3.0
1,0.0,9.0,8.0,4.0,9.0,0.0,0.0
2,3.0,3.0,3.0,6.0,12.0,1.0,1.0
3,1.0,6.0,6.0,3.0,11.0,0.0,0.0
4,6.0,2.0,2.0,5.0,5.0,2.0,2.0
...,...,...,...,...,...,...,...
40450,7.0,1.0,1.0,6.0,9.0,4.0,3.0
40451,11.0,0.0,0.0,5.0,3.0,6.0,8.0
40452,5.0,2.0,2.0,3.0,10.0,2.0,2.0
40453,1.0,8.0,7.0,4.0,11.0,0.0,0.0
40454,7.0,1.0,1.0,4.0,7.0,3.0,3.0

In [12]:
diamonds_kbin_w.to_csv('../../../001data/003preprocessing/002feature_engineering/diamonds_kbinsw.csv')

---

## KBins test

In [13]:
kbin_est.fit(diamonds_test_kbin)
diamonds_test_kbin = kbin_est.transform(diamonds_test_kbin)

In [14]:
diamonds_test_kbin

array([[ 6.,  3.,  3., ...,  6.,  2.,  3.],
       [10.,  1.,  1., ...,  7.,  4.,  5.],
       [11.,  0.,  1., ...,  5.,  5.,  6.],
       ...,
       [ 6.,  3.,  3., ..., 10.,  2.,  3.],
       [ 8.,  3.,  3., ...,  5.,  2.,  3.],
       [ 3.,  6.,  6., ..., 10.,  0.,  1.]])

In [15]:
diamonds_test_kbin = pd.DataFrame(diamonds_test_kbin)

In [16]:
diamonds_test_kbin.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

C:\Users\marym\AppData\Local\Temp\ipykernel_7004\834382323.py:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  diamonds_test_kbin.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

In [17]:
diamonds_test_kbin

,proportion_kbw,depth/carat_kbw,table/carat_kbw,x/y_kbw,depth/table_kbw,volume/table_kbw,volume/depth_kbw
0,6.0,3.0,3.0,1.0,6.0,2.0,3.0
1,10.0,1.0,1.0,1.0,7.0,4.0,5.0
2,11.0,0.0,1.0,7.0,5.0,5.0,6.0
3,7.0,2.0,2.0,3.0,12.0,3.0,4.0
4,4.0,5.0,5.0,3.0,8.0,1.0,2.0
...,...,...,...,...,...,...,...
13480,5.0,4.0,4.0,6.0,9.0,1.0,2.0
13481,6.0,3.0,3.0,4.0,10.0,2.0,3.0
13482,6.0,3.0,3.0,7.0,10.0,2.0,3.0
13483,8.0,3.0,3.0,3.0,5.0,2.0,3.0
13484,3.0,6.0,6.0,3.0,10.0,0.0,1.0

In [18]:
diamonds_test_kbin.to_csv('../../../001data/003preprocessing/002feature_engineering/diamonds_test_kbins.csv')

---

## Without test

In [19]:
kbin_est.fit(diamonds_kbin)
diamonds_kbin = kbin_est.transform(diamonds_kbin)

In [20]:
diamonds_kbin

array([[ 8.,  1.,  1., ...,  8.,  5.,  4.],
       [ 1.,  9.,  8., ...,  9.,  0.,  0.],
       [ 4.,  3.,  3., ..., 12.,  2.,  2.],
       ...,
       [ 7.,  2.,  2., ..., 10.,  4.,  3.],
       [ 1.,  9.,  7., ..., 11.,  0.,  0.],
       [ 8.,  1.,  1., ...,  7.,  5.,  4.]])

In [21]:
diamonds_kbin = pd.DataFrame(diamonds_kbin)

In [22]:
diamonds_kbin.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

C:\Users\marym\AppData\Local\Temp\ipykernel_7004\1707637954.py:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  diamonds_kbin.set_axis([['proportion_kbw', 'depth/carat_kbw', 'table/carat_kbw', 'x/y_kbw', 'depth/table_kbw', 'volume/table_kbw', 'volume/depth_kbw']], axis='columns', inplace=True)

In [23]:
diamonds_kbin

,proportion_kbw,depth/carat_kbw,table/carat_kbw,x/y_kbw,depth/table_kbw,volume/table_kbw,volume/depth_kbw
0,8.0,1.0,1.0,6.0,8.0,5.0,4.0
1,1.0,9.0,8.0,5.0,9.0,0.0,0.0
2,4.0,3.0,3.0,8.0,12.0,2.0,2.0
3,2.0,7.0,6.0,4.0,11.0,0.0,0.0
4,8.0,2.0,2.0,6.0,5.0,4.0,3.0
...,...,...,...,...,...,...,...
40450,8.0,1.0,1.0,7.0,9.0,6.0,4.0
40451,12.0,0.0,0.0,6.0,3.0,8.0,9.0
40452,7.0,2.0,2.0,4.0,10.0,4.0,3.0
40453,1.0,9.0,7.0,5.0,11.0,0.0,0.0
40454,8.0,1.0,1.0,5.0,7.0,5.0,4.0

In [24]:
diamonds_kbin.to_csv('../../../001data/003preprocessing/002feature_engineering/diamonds_kbins.csv')